### ISSUE TITLE
Optional block printable ascii support

### ISSUE THREAD

**Issue by Patrick-Github404** [openemv/tr31#1]
Hello,

I hope you're doing well. I wanted to bring up an issue I encountered while using your tool. It appears that your tool currently processes optional blocks only in HEX format and does not support printable ASCII.

According to IBM's documentation found at [Linux on Systems](https://www.ibm.com/docs/en/linux-on-systems?topic=data-tr-31-optional-block), as well as [z/OS 2.2.0](https://www.ibm.com/docs/en/zos/2.2.0?topic=keys-tr-31-optional-data-build-csnbt31o-csnet31o), there are instances where optional blocks may contain printable ASCII characters.

For example, the optional block "KS10DE#GBIC#OPT1" is mentioned in these documents. As it stands, your tool does not seem to handle this scenario, as it requires HEX input for optional blocks.

I kindly request that you consider enhancing your tool to support printable ASCII in optional blocks in addition to HEX. This would greatly improve its usability and compatibility with industry standards and documentation.

In return, we would be honored to promote your TR-31 package to IBM Crypto Labs.

Our Team is in long-term direct contact with the IBM Crypto labs, who are responsible for the Development of the IBM Crypto APIs around their HSM productline: IBM 4769, IBM 4770. 

Thank you for your attention to this matter. If you have any questions or require further clarification, please don't hesitate to reach out.

Best regards
Patrick

**Comment by leonlynch** [comment]
Hi Patrick,

Thank you for reaching out. I'm _very_ keen to know more about your requirements and to enhance the TR-31 library and tool accordingly. And my apologies for taking so long to reply.

You are indeed correct that version `0.4.6` and older only allowed HEX digits for optional block payloads. However, for version `0.5.0` and later, specific formats are allowed for specific optional blocks in accordance with the various standards: ANSI X9.143, ASC X9 TR-31 and ISO 20038. For optional block `KS`, it is required to be `0x18` bytes in length and consisting only of HEX digits:
![image](https://github.com/openemv/tr31/assets/2271766/49efbf1c-731b-43f4-bc52-9ddf3aa17010)


I'm unfamiliar with the DK/GBIC specification and would love to know more about it. Are you able to share the full DK/GBIC specification with me?

I would also like to know more about how your are using the library or tool. The enforcement of the individual optional block formats is implemented in the `tr31` library, while only the parsing and output (both of which of course make assumptions about the optional block format) is performed in `tr31-tool`. It would be very useful to know:
* Are you using the `tr31` library or are you using `tr31-tool`?
* Are you using it to create key blocks or are you using it to decode/decrypt key blocks, or both?

The interesting challenge is to know how to interpret the content of optional block `KS` depending on whether it follows the ANSI X9.143 / ASC X9 TR-31 standards, or follows the DK/GBIC specification. If you are using either the library or tool only to create key blocks, then an existing library function can be used to create arbitrary key blocks with any format, and the tool can be updated with a new command line option that does the same. However, if you are using either the library or the tool to decode/decrypt key blocks, then both would need some way to know that a different specification is being followed, both for validation/correctness during decoding as well as for display by the tool. Can you provide me with some examples of what you are doing with the library and/or tool?

Thank you again for reaching out and I look forward to your reply.

Kind regards,
Leon

**Comment by Patrick-Github404** [comment]
Hi Leon

In ISO 20038, you will find all the essential information regarding the OptBlock in the case of KS, including details about its data structure and the fact that this OptBlock can be in printable ASCII format. However, please note that we cannot share the ISO due to licensing restrictions.

It's important to clarify that the content related to KS10DE#GBIC#MMK1 is not specified within ISO 20038. So far, we have only obtained this information from the Export File (.xml) itself and from an official publication we found on IBM's website.

As of now, we have not come across any documents from the DK (presumably referring to a standards organization) that define the content of the OptBlock KS10DE#GBIC#MMK1.


**Are you using the tr31 library or are you using tr31-tool?**
I've been using the tr31-tool and not the library

**Are you using it to create key blocks or are you using it to decode/decrypt key blocks, or both?**
Both


Kind regards,
Patrick

**Comment by leonlynch** [comment]
Hi Patrick,

Thank you again for your interest in this project.

> In ISO 20038, you will find all the essential information regarding the OptBlock in the case of KS, including details about its data structure and the fact that this OptBlock can be in printable ASCII format. However, please note that we cannot share the ISO due to licensing restrictions.

Thankfully I already own a copy of ISO 20038:2017 because I needed it to implement format version `E`. However, ISO 20038:2017 Annex A.2.8 Table A.8 nonetheless indicates that optional block `KS` is "encoded in hex-ASCII":
![image](https://github.com/openemv/tr31/assets/2271766/1a2d815d-296a-4a8b-ade6-ffd2fc2ae94e)
From what I could see on iso.org there isn't a newer version of ISO 20038 available yet. Are you using a different version of ISO 20038 that allows non-hex digits for optional block `KS`?

> As of now, we have not come across any documents from the DK (presumably referring to a standards organization) that define the content of the OptBlock KS10DE#GBIC#MMK1.

I was not able to find any further information regarding DK/GBIC or the exact formatting of `KS10DE#GBIC#MMK1` in any of the other documentation I have, nor anywhere on the internet. But as you've mentioned, treating it as printable ASCII instead of HEX is the next step.

Thank you for sharing your uses of `tr31-tool` as that helps me put your needs into perspective. Do you perhaps have a few sample/test key blocks that contain `KS10DE#GBIC#MMK1` that you are able to share? I would be curious to see what other proprietary attributes and optional blocks may be present in those.

I've also been looking at the updated documentation at [z/OS 2.5.0](https://www.ibm.com/docs/en/zos/2.5.0?topic=ktf-x9143-tr-31-key-block-header-optional-block-data) and would eventually like to identify and decode IBM CCA key blocks with mode of use `1` and containing the IBM control vector optional block described [here](https://www.ibm.com/docs/en/zos/2.5.0?topic=ktf-x9143-tr-31-key-block-header-optional-block-data#sharedTR31__title__5). Do you perhaps have any such sample/test key blocks that you are able to share?

In the meantime I have started refactoring the library to facilitate your request. Currently the validation and decoding of optional blocks happen immediately during import and the encoding of optional blocks happens during export. Therefore, the internal representation of optional blocks already uses their formatting specified by ANSI X9.143. My intention is to change this such that the parsing, validation and decoding are separate activities, and that the internal representation is printable ASCII instead. Only parsing and basic validation will then occur during import, while full validation and decoding will occur in new decoder API functions. Similarly, encoding will then move to the existing add API functions while the export activity can use the internal format as-is. Finally `tr31-tool` can then be updated with the ability to create arbitrary optional blocks for proprietary uses (to cater for `KS10DE#GBIC#MMK1`) and can then optionally disable import validation (eg `--import-no-validation`) to allow display of key blocks that contain non-standard elements. I anticipate that once the IBM CCA attributes and optional block are supported, it would not be necessary to disable validation for those key blocks during import. However, unless there is a clear way to identify DK/GBIC key blocks with certainty during import, it would probably be necessary to always instruct `tr31-tool` to disable validation (eg `--import-no-validation`) when importing such key blocks for display. 

Let me know if the above makes sense to you.

Kind regards,
Leon

**Comment by Patrick-Github404** [comment]
Hello Leon,

I apologize for the late response. Yes, we are currently in the process of calculating test keys, and we will send them to you as soon as possible.

- **Let me know if the above makes sense to you.** -> totaly makes sense


Kind regards,
Patrick

**Comment by leonlynch** [comment]
Hi Patrick,

I'm just following up on whether you were able to generate some test key blocks that reflects the proprietary IBM and DK/GBIC features? The refactoring is approaching a stage where testing with representative data would be valuable.

Kind regards,
Leon

**Comment by leonlynch** [comment]
Hi Patrick,

I'm just following up on whether you were able to generate some test key blocks that reflects the proprietary IBM and DK/GBIC features? The refactoring is approaching a stage where testing with representative data would be valuable.

Kind regards,
Leon

**Comment by leonlynch** [comment]
Hi Patrick,

Let me know whether https://github.com/openemv/tr31/releases/tag/0.6.0 suits your needs and feel free to reach out with further suggestions.

Kind regards,
Leon

**Comment by Patrick-Github404** [comment]
Dear Leon,
I hope this email finds you well. I want to sincerely apologize for the delay in getting back to you; there has been a lot on my plate recently, coupled with the holidays.
I was in the process of providing you with test keys, but upon further consideration, it seems unnecessary as I've successfully tested the tool, and it's functioning flawlessly. The TR31 Block is being calculated correctly.
I appreciate the update you provided. Is there an alternative method, aside from GitHub, through which I can reach out to you?
Thank you for your understanding.
Best regards,Patrick
   Am Donnerstag, 28. Dezember 2023 um 11:09:01 MEZ hat Leon Lynch ***@***.***> Folgendes geschrieben:  
 
 


Hi Patrick,

Let me know whether https://github.com/openemv/tr31/releases/tag/0.6.0 suits your needs and feel free to reach out with further suggestions.

Kind regards,
Leon

**Comment by leonlynch** [comment]
Hi Patrick,

I'm glad to hear that the release is serving you well!

> I was in the process of providing you with test keys, but upon further consideration, it seems unnecessary

You are still most welcome to provide those test keys, especially if you have accompanying test KBPKs as well. I hand-crafted test data for the unit tests and it would be great to replace that with test keys created by an actual IBM HSM.

> Is there an alternative method, aside from GitHub, through which I can reach out to you?

You are welcome to use the email address on my [github profile](https://github.com/leonlynch). If my spam filter catches it and you don't hear from me timeously, please let me know in this github thread then I know to go find your email in my spam folder. I look forward to your email.

Kind regards,
Leon
